version: "3"

services:
  elk:
    image: sebp/elk:640
    container_name: elk-filebeat_elk
    hostname: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./data/elasticsearch:/var/lib/elasticsearch
    networks:
      - elk-filebeat

  filebeat:
    image: prima/filebeat:6
    container_name: elk-filebeat_filebeat
    volumes:
      - ./data/filebeat/config/filebeat.yml:/filebeat.yml
      - ./data/filebeat/data:/data
      - /var/lib/docker/containers:/var/lib/docker/containers
    depends_on:
      - elk
    links:
      - elk
    networks:
      - elk-filebeat

networks:
  elk-filebeat:
    external: true
































