version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest 
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./data/streaming/zookeeper/data:/data
      - ./data/streaming/zookeeper/logs:/datalog
    networks:
      - streaming_net

  kafka1:
    image: wurstmeister/kafka:latest 
    container_name: kafka-cluster1
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/streaming/logs/cluster1:/kafka
    ports:
      - 9091:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.20.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_JVM_PERFORMANCE_OPTS: " -Xmx256m -Xms256m"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091
      JMX_PORT: 9999
      KAFKA_ADVERTISED_PORT: 9091
    networks:
      - streaming_net

  kafka2:
    image: wurstmeister/kafka:latest 
    container_name: kafka-cluster2
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/streaming/logs/cluster2:/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.20.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_JVM_PERFORMANCE_OPTS: " -Xmx256m -Xms256m"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      JMX_PORT: 9999
      KAFKA_ADVERTISED_PORT: 9092
    networks:
      - streaming_net

  kafka3:
    image: wurstmeister/kafka:latest 
    container_name: kafka-cluster3
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/streaming/logs/cluster3:/kafka
    ports:
      - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.20.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_JVM_PERFORMANCE_OPTS: " -Xmx256m -Xms256m"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9093
      JMX_PORT: 9999
      KAFKA_ADVERTISED_PORT: 9093
    networks:
      - streaming_net

  kafka-manager:
    image: sheepkiller/kafka-manager:latest                 # 镜像：开源的web管理kafka集群的界面
    container_name: kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_BROKERS: kafka1:9091,kafka2:9092,kafka3:9093
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    links:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
    ports:
      - 9000:9000
    networks:
      - streaming_net

networks:
  streaming_net:
    external: true
















