version: "3"

services:
   jenkins:
      image: jenkins/jenkins:lts
#      image: jenkins
      container_name: jenkins
      restart: always
      privileged: true
      user: root
      volumes:
        - ./data/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime
      ports:
        - 8001:8080
        - 5000:5000
      environment:
        JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'
      networks:
        - custom_net

networks:
  custom_net:
    external:
      name: app_net
